/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JZNOdNNrVf7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Products() {
  return (
    <section className="grid grid-cols-1 gap-6 p-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 md:p-6">
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product Category 1"
          width={400}
          height={400}
          className="object-cover w-full aspect-square"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Outdoor Gear</h3>
          <p className="text-sm text-muted-foreground">Explore the great outdoors</p>
          <div className="flex items-center justify-between">
            <p className="text-base font-semibold">$99.99</p>
            <Button size="sm">Shop</Button>
          </div>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product Category 2"
          width={400}
          height={400}
          className="object-cover w-full aspect-square"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Kitchen Essentials</h3>
          <p className="text-sm text-muted-foreground">Upgrade your culinary experience</p>
          <div className="flex items-center justify-between">
            <p className="text-base font-semibold">$49.99</p>
            <Button size="sm">Shop</Button>
          </div>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product Category 3"
          width={400}
          height={400}
          className="object-cover w-full aspect-square"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Home Decor</h3>
          <p className="text-sm text-muted-foreground">Elevate your living space</p>
          <div className="flex items-center justify-between">
            <p className="text-base font-semibold">$79.99</p>
            <Button size="sm">Shop</Button>
          </div>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product Category 4"
          width={400}
          height={400}
          className="object-cover w-full aspect-square"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Tech Accessories</h3>
          <p className="text-sm text-muted-foreground">Enhance your digital life</p>
          <div className="flex items-center justify-between">
            <p className="text-base font-semibold">$29.99</p>
            <Button size="sm">Shop</Button>
          </div>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product Category 5"
          width={400}
          height={400}
          className="object-cover w-full aspect-square"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Apparel</h3>
          <p className="text-sm text-muted-foreground">Stylish clothing for every occasion</p>
          <div className="flex items-center justify-between">
            <p className="text-base font-semibold">$59.99</p>
            <Button size="sm">Shop</Button>
          </div>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product Category 6"
          width={400}
          height={400}
          className="object-cover w-full aspect-square"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Beauty &amp; Personal Care</h3>
          <p className="text-sm text-muted-foreground">Pamper yourself with our products</p>
          <div className="flex items-center justify-between">
            <p className="text-base font-semibold">$39.99</p>
            <Button size="sm">Shop</Button>
          </div>
        </div>
      </div>
    </section>
  )
}
