/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JZNOdNNrVf7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"

export function Products() {
  const [products, setProducts] = useState([])

  useEffect(() => {
    // Replace the URL with the path to your JSON file
    fetch('/products.json')
      .then(response => response.json())
      .then(data => setProducts(data))
  }, [])

  return (
    <section className="grid grid-cols-1 gap-6 p-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 md:p-6">
      {products.map(product => (
        <div key={product.name} className="relative overflow-hidden rounded-lg group">
          <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
            <span className="sr-only">View</span>
          </Link>
          <img
            src={product.imagePath}
            alt={product.name}
            width={400}
            height={400}
            className="object-cover w-full aspect-square"
          />
          <div className="p-4 bg-background">
            <h3 className="text-lg font-semibold">{product.name}</h3>
            <p className="text-sm text-muted-foreground">{product.description}</p>
            <div className="flex items-center justify-between">
              <p className="text-base font-semibold">${product.price}</p>
              <Button size="sm">Shop</Button>
            </div>
          </div>
        </div>
      ))}
    </section>
  )
}